"""
GitHub API Routes

Endpoints for 1-click Pull Request creation and AI-powered fix generation.
"""

import os
import re
import difflib
import logging
from typing import Optional, Dict, Any
from flask import Blueprint, request, jsonify, session, current_app

from services.github_service import GitHubAPIClient
from reporting.fix_generator import FixGenerator
from models.user import User
from auth.jwt_utils import JWTManager
import config

logger = logging.getLogger(__name__)

github_bp = Blueprint('github_api', __name__, url_prefix='/api/github')


def _get_current_user_id() -> Optional[int]:
    """Extract user_id from session or Bearer token"""
    token = session.get('jwt_access_token')
    if not token and 'Authorization' in request.headers:
        auth_hdr = request.headers['Authorization'].strip()
        if auth_hdr.startswith('Bearer '):
            token = auth_hdr[7:].strip()
    if token:
        try:
            payload = JWTManager.verify_token(token)
            if not JWTManager.is_blacklisted(token):
                return payload.get('user_id') or payload.get('sub')
        except Exception:
            pass
    return None


def _get_github_token(payload_token: Optional[str] = None) -> Optional[str]:
    """Retrieve GitHub token with multiple fallbacks"""
    # 1. Directly provided in request body
    if payload_token and payload_token.strip():
        return payload_token.strip()

    # 2. In Flask session
    token = session.get('github_access_token')
    if token:
        return token

    # 3. From User record in DB
    user_id = _get_current_user_id()
    if user_id:
        try:
            user = User.get_by_id(user_id)
            if user and user.github_access_token:
                session['github_access_token'] = user.github_access_token
                return user.github_access_token
        except Exception as e:
            logger.warning(f"Error fetching user GitHub token from DB: {e}")

    # 4. Fallback environment token
    return os.getenv('GITHUB_TOKEN', '').strip() or None


@github_bp.route('/raise-pr', methods=['POST'])
def raise_pr():
    """
    1-Click Pull Request creation endpoint.
    Creates a branch, commits the remediated file content, and opens a Pull Request.
    """
    user_id = _get_current_user_id()
    if not user_id and not session.get('jwt_access_token'):
        return jsonify({'error': 'Authentication required. Please log in.'}), 401

    data = request.get_json(silent=True) or {}
    owner = data.get('owner', '').strip()
    repo = data.get('repo', '').strip()
    file_path = data.get('file_path', '').strip()
    file_content = data.get('file_content', '')
    title = data.get('title', '').strip()
    body = data.get('body', '').strip()
    commit_message = data.get('commit_message', '').strip()
    base_branch = data.get('base_branch', '').strip() or None
    req_token = data.get('github_token', '').strip() or None

    # Support 'repo' as 'owner/repo' combined string
    if not owner and '/' in repo:
        parts = repo.split('/', 1)
        owner, repo = parts[0].strip(), parts[1].strip()

    if not owner or not repo:
        return jsonify({'error': 'Target repository (owner and repo) is required.'}), 400

    if not file_path:
        return jsonify({'error': 'File path to patch is required.'}), 400

    if not file_content:
        return jsonify({'error': 'Patched file content cannot be empty.'}), 400

    github_token = _get_github_token(req_token)
    if not github_token:
        return jsonify({
            'error': 'GitHub access token not found. Please link your GitHub account or supply a Personal Access Token.'
        }), 401

    if not title:
        title = f"Fix: Remediate security issue in {os.path.basename(file_path)}"

    if not body:
        finding_desc = data.get('description', 'Remediation suggested by automated code security analysis.')
        body = (
            f"## 🛡️ AI Security & Quality Remediation\n\n"
            f"This pull request addresses a potential issue detected during code analysis.\n\n"
            f"### Details\n"
            f"- **Target File:** `{file_path}`\n"
            f"- **Issue Summary:** {title}\n"
            f"- **Description:** {finding_desc}\n\n"
            f"### Verification\n"
            f"Please review the diff carefully, run your test suite, and merge when satisfied.\n\n"
            f"---\n"
            f"*Generated by AI Code Review Platform*"
        )

    client = GitHubAPIClient(access_token=github_token)

    try:
        pr_result = client.create_security_pr(
            owner=owner,
            repo=repo,
            title=title,
            body=body,
            file_path=file_path,
            file_content=file_content,
            commit_message=commit_message or title,
            base_branch=base_branch
        )
        if not pr_result:
            return jsonify({'error': 'Failed to create Pull Request on GitHub.'}), 500

        logger.info(f"Successfully raised PR #{pr_result.get('number')} on {owner}/{repo}")
        return jsonify({
            'status': 'success',
            'url': pr_result.get('url'),
            'html_url': pr_result.get('url'),
            'pr_number': pr_result.get('number'),
            'branch': pr_result.get('branch'),
            'base_branch': pr_result.get('base_branch')
        }), 201

    except RuntimeError as e:
        return jsonify({'error': str(e)}), 400
    except Exception as e:
        logger.error(f"Failed to raise PR for {owner}/{repo}: {e}", exc_info=True)
        return jsonify({'error': f'Failed to raise Pull Request: {str(e)}'}), 500


@github_bp.route('/generate-fix', methods=['POST'])
def generate_fix():
    """
    Generate an AI-suggested code remediation and unified diff for a finding.
    """
    user_id = _get_current_user_id()
    if not user_id and not session.get('jwt_access_token'):
        return jsonify({'error': 'Authentication required.'}), 401

    data = request.get_json(silent=True) or {}
    uid = data.get('uid', '').strip()
    file_path = data.get('file_path', '').strip()
    finding = data.get('finding', {})

    if not file_path:
        return jsonify({'error': 'file_path is required.'}), 400

    # Locate uploaded file on disk
    original_content = ""
    file_found = False
    if uid:
        try:
            upload_folder = current_app.config.get('UPLOAD_FOLDER', 'uploads')
            target_path = os.path.abspath(os.path.join(upload_folder, uid, file_path))
            base_path = os.path.abspath(os.path.join(upload_folder, uid))
            if target_path.startswith(base_path) and os.path.exists(target_path) and os.path.isfile(target_path):
                with open(target_path, 'r', encoding='utf-8', errors='replace') as f:
                    original_content = f.read()
                file_found = True
        except Exception as e:
            logger.warning(f"Could not read local file {file_path} for {uid}: {e}")

    # If file content was passed directly
    if not file_found and data.get('original_content'):
        original_content = data['original_content']
        file_found = True

    # Generate fix suggestions using FixGenerator
    fix_gen = FixGenerator()
    suggestion = fix_gen.generate_fix_suggestion(finding, context={'file_path': file_path})

    explanation = "\n".join(suggestion.get('steps', [])) or suggestion.get('remediation', '')
    patched_content = original_content

    # Attempt LLM-assisted remediation if an LLM client is configured
    llm_patched = _generate_llm_patch(original_content, finding, file_path)
    if llm_patched:
        patched_content = llm_patched
    elif not original_content:
        # Fallback to code template from FixGenerator
        code_example = suggestion.get('code_example', {})
        if code_example and 'fixed' in code_example:
            patched_content = f"// Remediation Example for {finding.get('title', 'Issue')}\n" + code_example['fixed']
            explanation = explanation or "Automated template-based remediation."

    # Compute unified diff
    diff_lines = list(difflib.unified_diff(
        original_content.splitlines(keepends=True),
        patched_content.splitlines(keepends=True),
        fromfile=f"a/{file_path}",
        tofile=f"b/{file_path}",
        n=3
    ))
    diff_str = "".join(diff_lines)

    return jsonify({
        'status': 'success',
        'file_path': file_path,
        'original_content': original_content,
        'patched_content': patched_content,
        'diff': diff_str,
        'explanation': explanation,
        'difficulty': suggestion.get('difficulty', 'MEDIUM'),
        'estimated_time': suggestion.get('estimated_time', '15 minutes'),
        'references': suggestion.get('references', [])
    }), 200


def _generate_llm_patch(code: str, finding: Dict[str, Any], file_path: str) -> Optional[str]:
    """Use configured LLM to generate precise patched code"""
    if not code or len(code) > 40000:
        return None

    try:
        from llm_agents.llm_factory import LLMFactory
        client = LLMFactory.create_analysis_client()
        if not client:
            return None

        issue_title = finding.get('title') or finding.get('type', 'Security Issue')
        issue_desc = finding.get('description', '')
        line_no = finding.get('line_number') or finding.get('line')

        line_hint = f" around line {line_no}" if line_no else ""
        prompt = (
            f"You are an expert security engineer. Remediate the following security/code quality issue:\n"
            f"File: {file_path}\n"
            f"Issue: {issue_title}{line_hint}\n"
            f"Details: {issue_desc}\n\n"
            f"Original Code:\n"
            f"```\n{code}\n```\n\n"
            f"Instructions:\n"
            f"1. Fix the issue cleanly with best security practices.\n"
            f"2. Maintain the existing architecture, functions, and style.\n"
            f"3. Return ONLY the complete modified source code without any markdown explanation or code fences.\n"
        )

        response = client.complete(
            prompt=prompt,
            system_prompt="You are an automated code remediation agent. Output only raw code.",
            temperature=0.1,
            max_tokens=4000
        )
        if response and response.strip():
            cleaned = response.strip()
            # Strip markdown code blocks if the LLM wrapped it
            if cleaned.startswith("```"):
                cleaned = re.sub(r'^```[a-zA-Z0-9_-]*\n', '', cleaned)
                cleaned = re.sub(r'\n```$', '', cleaned)
            return cleaned.strip()
    except Exception as e:
        logger.warning(f"LLM patch generation failed: {e}")

    return None
